name: sphinx-build

on:
  push:
    paths:
      - 'source/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Placeholder
      run: |
        echo "Placeholder"
        pwd
        ls
    - name: Sphinx Make
      run: |
        make clean
        make html
        last_commit=`git log -1 --pretty=%B`
        export COMMIT_MESSAGE=`echo $last_commit "[auto-build]"`
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: {{env.COMMIT_MESSAGE}}
