name: sphinx-build-deploy

on:
  workflow_dispatch:
  push:
    paths:
      - 'source/**'

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Sphinx Make
      id: sphinx
      run: |
        make clean
        make html
        tar -czvf ./docs.tar.gz ./docs
        # last_commit=`git log -1 --pretty=%B`
        # export MSG=`echo "[auto-build] ${last_commit}"`
        # echo "commit_message=${MSG}" >> $GITHUB_OUTPUT
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # make this the gzip tar
        path: ./docs.tar.gz
        
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
