name: sphinx-build

on:
  push:
    branches: [ master ]

env:
  GITACTION: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Placeholder
      run: |
        echo "Placeholder"
        pwd
        ls
    - name: Sphinx Make
      run: |
        make clean
        make html
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/html/*
        git add docs/plot_directive/*
        git commit -m "automatic commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
